---
- name: packages install
  hosts: centos
  gather_facts: false
  vars:
    pkg1: ['curl', 'httpd', 'wget', 'vim'] #  one method to list the items
    pkg2: # method 2 to list the items
    - 'curl'
    - 'httpd'
    - 'wget'
    - 'vim'
  tasks:
  - name: install the list of packages
    debug: var=pkg1

#  tasks:
#  - name: install the list of packages using 2 method
#    debug: var=pkg2
