---
- 
  hosts: all
  gather_facts: true
  become: yes
  tasks:
          - name: filter memory facts
            setup:
                    filter: ansible_memory_mb
          - name: show memory nocache values
            debug:
                    var: ansible_memory_mb.nocache

          - name: display cpu
            debug:
                    msg:  "cpu : {{ ansible_facts['processor_vcpus']}}"
                    #msg: "{{ ansible_facts['nodename']}}"
...
