#!/bin/ansible
- hosts: workerNodeOne
  gather_facts: False
  vars_prompt:
    - name: "Username"
      prompt: "Enter User name"
      private: no
    - name: password
      prompt: "please enter the password"
      private: no

  tasks:
    - name: Ansible prompt example.
      debug:
        msg: 
        - "{{ Username }}"
    - name: Creating user Account
      user:
        name: "{{ Username }}"
        state: present
        shell: /bin/bash
        password: "{{ password | password_hash('sha512') }}"
