---
- name: system configuration for WORKERS
  hosts: test
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no

  tasks:
  - name: Install packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - curl

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Create containerd config file
    file:
        path: "/etc/modules-load.d/containerd.conf"
        state: "touch"

  - name: Add conf for containerd
    blockinfile:
         path: "/etc/modules-load.d/containerd.conf"
         block: |
               overlay
               br_netfilter

  - name: modprobe
    shell: |
             modprobe overlay
             modprobe br_netfilter

  - name: Set system configurations for Kubernetes networking
    file:
       path: "/etc/sysctl.d/99-kubernetes-cri.conf"
       state: "touch"

  - name: Add conf for containerd
    blockinfile:
       path: "/etc/sysctl.d/99-kubernetes-cri.conf"
       block: |
               net.bridge.bridge-nf-call-iptables = 1
               net.ipv4.ip_forward = 1
               net.bridge.bridge-nf-call-ip6tables = 1

  - name: Apply new settings
    shell: |
             sysctl --system
             sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
             swapoff -a

  - name: Docker installation
    get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

  - name: Install docker and its dependecies
    yum: 
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io

  - name: restart docker-services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
    - docker
    - containerd



